# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='tech',
            field=models.CharField(max_length=50),
        ),
    ]
